name: GotCraftTutorial
version: '1.0-SNAPSHOT'
main: me.lubomirstankov.gotCraftTutorial.GotCraftTutorial
api-version: '1.21'
author: lubomirstankov
description: A comprehensive tutorial system for Minecraft servers

commands:
  tutorial:
    description: Start or stop the server tutorial
    usage: /<command> [stop]
    aliases: [guide]

  guide:
    description: Alias for /tutorial command
    usage: /<command> [stop]

  guideadmin:
    description: Admin commands for managing the tutorial system
    usage: /<command> <setpoint|settitle|setmotd|reload|info> [args...]
    permission: gotcrafttutorial.admin
    aliases: [gadmin]

permissions:
  gotcrafttutorial.admin:
    description: Allows access to tutorial admin commands
    default: op
